#pragma once
#ifdef USERMOD_BASEBALL_API

#include "wled.h"

// AI: below section was generated by an AI
// Baseball API usermod for WLED
// Provides live scores and next-game info for user-selected teams using API-Sports Baseball API
// Implements subscription/filter pattern as in weather_api
//
// - User can select favorite teams (by team ID or name)
// - Polls API hourly for next-game info
// - Polls every 15s during live games
// - Uses WLED timezone settings for API requests
// - Efficient JSON filtering with ArduinoJson
// - Configurable via WLED Usermod UI

// Callback type for baseball API values. JsonVariant is valid only during the callback.
typedef void (*BaseballValueCallback)(JsonVariant value);

struct BaseballSubscription {
  const char*          path;      // dot-notation, e.g. "games.0.scores.home.total"
  BaseballValueCallback callback; // called with the parsed value after each fetch
};

#ifndef BASEBALL_API_MAX_SUBS
#define BASEBALL_API_MAX_SUBS 8
#endif
#ifndef BASEBALL_API_FILTER_DOC_SIZE
#define BASEBALL_API_FILTER_DOC_SIZE 512
#endif
#include "const.h"
#ifndef BASEBALL_API_RESPONSE_DOC_SIZE
#define BASEBALL_API_RESPONSE_DOC_SIZE 256
#endif

struct BaseballTeamStyle {
  const char* teamId;
  const char* name;
  const char* initials;
  uint32_t primaryColor;
  uint32_t secondaryColor;
};

class UsermodBaseballAPI : public Usermod {
private:
  static const char _name[];
  static const char _keyEnabled[];
  static const char _keyApiKey[];
  static const char _keyTeam[];
  static const char _keyInterval[];

  bool _enabled = true;
  String apiKey;
  String timezone;
  unsigned long _lastFetch = 0;
  unsigned long _intervalMs = 3600000;
  bool _fetchPending = false;
  bool _lastFetchOk = false;
  String _lastError;
  char _lastUrl[160] = "";
  String lastGameId;
  bool gameLive = false;
  String lastScore;

  BaseballSubscription _subs[BASEBALL_API_MAX_SUBS];
  uint8_t _subCount = 0;

  void updateTimezone();
  void _doFetch();
  void _setFilterPath(JsonObject root, const char* path);
  JsonVariant _getByPath(JsonVariant root, const char* path);
  void setPollInterval(bool live);
  String getIanaTimezone(uint8_t wledTzId);
  void showScore(const String& score);
  void showNextGame(const String& info);
  void requestNextGame();
  void requestLiveScore(const String& gameId);
  void loadConfig();
  void saveConfig();
  void _handleApiResponse(const String& json);
  static const BaseballTeamStyle* _findTeamStyle(const String& teamId);

public:
  // Subscription system
  String favoriteTeam;
  bool subscribe(const char* path, BaseballValueCallback callback);
  void triggerFetch();
  bool isAvailable() const { return _lastFetchOk; }
  bool isGameLive() const { return gameLive; }
  const String& getLastScore() const { return lastScore; }
  const String& getFavoriteTeam() const { return favoriteTeam; }
  const BaseballTeamStyle* getTeamStyle(const String& teamId) const { return _findTeamStyle(teamId); }
  const BaseballTeamStyle* getFavoriteTeamStyle() const { return _findTeamStyle(favoriteTeam); }
  const char* getTeamInitials(const String& teamId) const;
  const char* getFavoriteTeamInitials() const;
  bool getTeamColors(const String& teamId, uint32_t& primaryColor, uint32_t& secondaryColor) const;
  bool getFavoriteTeamColors(uint32_t& primaryColor, uint32_t& secondaryColor) const;

  // WLED usermod interface
  void setup() override;
  void loop() override;
  void addToJsonInfo(JsonObject& root) override;
  void addToConfig(JsonObject& root) override;
  bool readFromConfig(JsonObject& root) override;
  void appendConfigData() override;
  uint16_t getId() override { return USERMOD_ID_BASEBALL_API; }
};

#endif // USERMOD_BASEBALL_API
